### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by Arinerron** [ImMilesahead/Linux-Process-Manager#1]
Are you still going to make this project? It actually sounds like a nice idea.
Saving the machine state... There are certain features I don't know how you'd do, but still.

Thanks!

**Comment by ImMilesahead** [comment]
It's not dead, I just havn't had a stable build of Linux lately, atleast one that would connect to WiFi consistently, So I've never been able to develop it further than the poor excuse for a project it is currently.
